config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mixins.home.urls')),
]

mixins/home/urls.py
from django.urls import path

from . import views
from .api import views as views_api

app_name = 'home'

urlpatterns = [
	path('', views.HomeIndexView.as_view(), name='index'),
	path('about', views.AboutView.as_view(), name='about'),
	path('contact', views.ContactView.as_view(), name='contact'),
	path('artciles', views.ArticleListView.as_view(), name='articles-list'),
	path('article/<int:pk>/download', views.ArticleDownloadView.as_view(), name='article-download'),
	path('article/<int:pk>/watch-online', views.ArticleWatchOnlineView.as_view(), name='article-watch-online'),
	path('add-contact', views_api.ContactCreateAPIView.as_view(), name='add-contact'),
]

mixins/home/models.py
from django.db import models


class Contact(models.Model):
	email = models.EmailField(unique=True)

	def __str__(self):
		return self.email
		

class Article(models.Model):
	name = models.CharField(max_length=80, unique=True)
	file = models.BooleanField(default=False)

	def __str__(self):
		return self.name

mixins/home/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
	
	class Meta:
		model = Contact
		fields = ['email']
		widgets = {
			'email': forms.EmailInput(attrs={
						'class': 'form-control',
						'placeholder': 'example@example.com'
					}
				),
		}

mixins/home/api/views.py
from rest_framework import generics

from .serializers import ContactSerializer


class ContactCreateAPIView(generics.CreateAPIView):
	serializer_class = ContactSerializer

mixins/home/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views import generic

from .models import Article
from .forms import ContactForm


class HomeMixin(object):

	def get_context_data(self, **kwargs):
		context = super(HomeMixin, self).get_context_data(**kwargs)
		context['number_of_visit'] = 100
		return context

	def get(self, request, *args, **kwargs):
		return super().get(request, *args, **kwargs)


class HomeIndexView(HomeMixin, generic.TemplateView):
	template_name = 'home/index.html'


class AboutView(HomeMixin, generic.TemplateView):
	template_name = 'home/about.html'
	

class ArticleListView(generic.ListView):
	model = Article
	template_name = 'home/articles-list.html' 
	context_object_name = 'articles'

	def get_queryset(self):
		return Article.objects.all()


class ArticleMixin(object):
	model = Article
	context_object_name = 'article'

	def build_response(self, article):
		return render(self.request, self.template_name, {'article': article})

	def get(self, request, pk, *args, **kwargs):
		article = get_object_or_404(Article, pk=pk)

		if not article.file:
			return render(request,
					'home/article-unavailable.html',
					{'article': article}
				)
		
		response = self.build_response(article)

		return response


class ArticleDownloadView(ArticleMixin, generic.DetailView):
	template_name = 'home/article-detail.html'


class ArticleWatchOnlineView(ArticleMixin, generic.DetailView):
	template_name = 'home/article-watch-online.html'

	def build_response(self, article):
		context = {
			'article': article,
			'desde': 'ArticleWatchOnlineView'
		}
		return render(self.request, self.template_name, context)


class ContactView(HomeMixin, generic.TemplateView):
	template_name = 'home/contact.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['form'] = ContactForm()
		return context

mixins/home/templates/home/about.html
{% extends 'base/base.html' %}

{% block title %} {{ block.super }} | About {% endblock %}

{% block content %} 
<div class="row">
	<div class="col s12">
		<h2>About</h2>
	</div>	
</div>
{% endblock%}

mixins/home/templates/home/article-detail.html
{% extends 'home/base.html' %}

{% block title %} Article: {{ article.name }} {% endblock %}

{% block content %}
<div class="row">
	<div class="col s12">
		<article class="card">
			<div class="card-content">
				<h3 class="card-title">Download success!!!</h3>
				<p>The article "{{article.name }}" was download succesfull!</p>
			</div>
			<div class="card-action">
				<a href="{% url 'home:articles-list' %}" class="btn blue darken-1"> <i class="material-icons left">arrow_back</i> Go Back!</a>
			</div>
		</article>
	</div>
</div>
{% endblock %}

mixins/home/templates/home/article-unavailable.html
{% extends "base/base.html" %}

{% block title %} Article: {{ article.name }} {% endblock %}

{% block content %}
<div class="row">
	<div class="col s12">
		<article class="card">
			<div class="card-content">
				<h3 class="card-title">Sorry... :(</h3>
				<p>The article "{{article.name }}" is not available.</p>
			</div>
			<div class="card-action">
				<a href="{% url 'home:articles-list' %}" class="btn blue darken-1"> <i class="material-icons left">arrow_back</i> Go Back!</a>
			</div>
		</article>
	</div>
</div>
{% endblock %}

mixins/home/templates/home/article-watch-online.html
{% extends 'home/base.html' %}

{% block title %} Article: {{ article.name }} {% endblock %}

{% block content %}
<div class="row">
	<div class="col s12">
		<article class="card">
			<div class="card-content">
				<h3 class="card-title">Watch online</h3>
				<p>The article "{{article.name }}" was watch online succesfull!</p>
			</div>
			<div class="card-action">
				<a href="{% url 'home:articles-list' %}" class="btn blue darken-1"> <i class="material-icons left">arrow_back</i> Go Back!</a>
			</div>
		</article>
	</div>
</div>
{% endblock %}

mixins/home/templates/home/articles-list.html
{% extends 'home/base.html' %}

{% load static %}

{% block title %} {{ block.super }} | Articles {% endblock %}

{% block content %}
<div class="row">
	{% for article in articles %}
	<div class="col s12 l6">
		<article class="card">
			<div class="card-image">
				<img src="{% static 'base/img/travis.png' %}">
			</div>
			<div class="card-content">
				<h4>{{ article.name }}</h4>
				<p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste nihil quae alias ratione minima officia sint exercitationem officiis odit dolor voluptas placeat asperiores, assumenda accusantium! Alias tenetur dignissimos distinctio asperiores.</p>
			</div>
			<div class="card-action">
				<a href="{% url 'home:article-watch-online' article.pk %}">Wacth <i class="material-icons left">watch</i></a>
				<a href="{% url 'home:article-download' article.pk %}">Download <i class="material-icons right">domain</i></a>
			</div>
		</article>
	</div>
	{% empty %}
	<div class="col s12 m10 offset-s1">
		<div class="card">
			<div class="card-content">
				<h4 class="card-title"> There arent' articles </h4>
			</div>
		</div>
	</div>
	{% endfor %}	
</div>
{% endblock %}

mixins/home/templates/home/base.html
{% extends 'base/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'home/css/home.css' %}">
{% endblock %}

{% block content %}
{% endblock %}

mixins/home/templates/home/contact.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %} {{ block.super }} | Contact {% endblock %}

{% block content %}
<div id="app">
	<div class="row">
		<div class="col s12">
			<a href="#" @click.prevent="newContact" class="btn blue darken-1 btn-floating"> <i class="material-icons">add</i></a>
		</div>
	</div>
	<article class="modal" id="modal-contact">
		<div class="modal-content">
			<h4> Contact Form </h4>	
			<div v-show="ocurrioUnError"> 
				<p :class="{'red-text': ocurrioUnError }"> ${ error } </p>
			</div>
			<form method="post">{% csrf_token %}
				<div class="input-field">
					<input type="email"
								 name="email"
								 v-model="contact.email"
								 id="email">
					<label for="email">Email</label>
				</div>
				<button type="button"
								@click.prevent="send" 
								class="btn blue darken-1" 
								id="btn-send-contact"> 
						<i class="material-icons right">send</i>
						Send
				</button>
			</form>
		</div>
	</article>
</div>		
{% endblock %}

{% block js %}
<script src="{% static 'base/js/vue.min.js' %}"></script>
<script src="{% static 'base/js/axios.min.js' %}"></script>
<script src="{% static 'home/js/home.js' %}"></script>
{% endblock %}

mixins/home/templates/home/index.html
{% extends 'base/base.html' %}

{% block title %} {{ block.super }} | Home {% endblock %}

{% block content %}
<div class="row">
	<div class="col s12">
		<div class="card">
			<div class="card-content">
				<h2 class="card-title"> Uso de los mixins de Django </h2>
			</div>
		</div>
	</div>
</div>
{% endblock %}

mixins/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>{% block title %} Uso de Mixins {% endblock %}</title>
	<link rel="stylesheet" href="{% static 'base/materialize/css/materialize.min.css' %}">
	<link rel="stylesheet" href="{% static 'base/materialize/font/icon.css' %}">	
	
	{% block css %} 
	<!-- Coloca los archivos css extras para tus apps-->
	{% endblock %}
</head>
<body>
	<main>
		<nav>
			<div class="nav-wrapper blue darken-3">
				<ul id="nav-mobile" class="hide-on-med-and-down">
					<li>
						<a href="{% url 'home:index' %}"> <i class="material-icons left">home</i> Home</a>
					</li>
					<li>
						<a href="{% url 'home:about' %}"> <i class="material-icons left">info</i>About</a>
					</li>
					<li>
						<a href="{% url 'home:articles-list' %}"><i class="material-icons left">list</i> Articles</a>
					</li>
					<li>
						<a href="{% url 'home:contact' %}"> <i class="material-icons left">phone</i>Contact</a>
					</li>
				</ul>
			</div>
		</nav>
		<div class="container" id="content">
		{% block content %}

		{% endblock %}
		</div>
	</main>
	<script src="{% static 'base/js/jquery.min.js' %}"> </script>
	<script src="{% static 'base/js/jquery.cookie.js' %}"> </script>
	<script src="{% static 'base/materialize/js/materialize.min.js' %}"></script>
	<script src="{% static 'base/js/materialize-init.js' %}"> </script>

	{% block js %} <!-- Coloca los archivos js extras para tus apps--> 
	{% endblock %}
</body>
</html>